### PR TITLE
Support secureProtocol and custom cipher list

### PR DESCRIPTION
**Pull request by zerob4wl**

### CODE REVIEW

**Comment by 75lb** [comment]
useful feature, thanks - I will look at this today.

**Comment by zerob4wl** [comment]
+up

**Comment by 75lb** [comment]
@zerob4wl could you tell me your use case for this feature please? Why would setting custom `secureProtocol` and `cipher` values be useful for you? 

Thanks, it will help me understand the issue and ensure we release something that covers everyone's needs.

**Comment by zerob4wl** [comment]
The TLS has some version and some times you need to set it and force to use just a certain version. In my case, the client say the web server must use TLS v1.2 and one of certain Cipher.

**Comment by 75lb** [comment]
These options have been implemented in local-web-server v2 (which is nearing completion). Please install the preview release: 

```
$ npm install local-web-server@next
```

then run `ws --help` to see the options, which include `--ciphers` and `--secure-protocol`.

Let me know if this solves your issue.

**Pull request closed without merging**
