### PR TITLE
Add type and main fields to package.json

### PR DESCRIPTION
**Pull request by bjornharrtell**
Rationale is that this appears to resolve usage via ts-node.

### CODE REVIEW

**Comment by 75lb** [comment]
Hi, could you post a test case that I can run to see local-web-server failing under ts-node please.. I use will also use it to confirm the fix works.

**Comment by 75lb** [comment]
Closing until I receive instructions on how to reproduce the issue, to see it failing

**Comment by bjornharrtell** [comment]
It's appeared to "resolved itself" as time and upgrades went along . ☺️

**Comment by 75lb** [comment]
ok, that's good thanks

**Pull request closed without merging**
